### ISSUE TITLE
Synapse shortcut is missing 1.1.2

### ISSUE THREAD

**Issue by p33k** [kooohei/brackets-synapse#24]
Updated to the new 1.1.2, now the shortcut for the extension is missing. (On the right bar) 

The Developer console shows
Error setting menu item shortcut: 1/command/Menus.js:820 (anonymous function)

**Comment by kooohei** [comment]
damn... sorry. now I fixed please try update.

**Comment by p33k** [comment]
icon is back, thanks :)
But when I add a new server and press append it just loads till forever and nothing happens.
Console shows: 
../brackets-synapse/modules/SettingManager.js:432 Uncaught TypeError: Cannot read property 'exec' of undefined

**Comment by kooohei** [comment]
I'm sooooooo sory><
I can't beleave me anymore ;-)

**Comment by p33k** [comment]
login works now :)
But it only shows folders on the server, no files

**Comment by p33k** [comment]
Errors:
1.
Objectcode: 530__proto__: Object 
../brackets-synapse/modules/RemoteManager.js:165 Objectcode: 530__proto__: Object

2.
 [node-error 5:21:10 AM] [Launcher] uncaught exception at top level, exiting. Error: write after end
    at writeAfterEnd (_stream_writable.js:130:12)
    at Socket.Writable.write (_stream_writable.js:178:5)
    at Socket.write (net.js:613:40)
    at FTP._send (C:\Users\peek\AppData\Roaming\Brackets\extensions\user\brackets-synapse\node\node_modules\ftp\lib\connection.js:1038:18)
    at Parser.<anonymous> (C:\Users\peek\AppData\Roaming\Brackets\extensions\user\brackets-synapse\node\node_modules\ftp\lib\connection.js:126:12)
    at Parser.EventEmitter.emit (events.js:98:17)
    at Parser._write (C:\Users\peek\AppData\Roaming\Brackets\extensions\user\brackets-synapse\node\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at Parser.Writable.write (_stream_writable.js:180:11)

extensions/default/DebugCommands/NodeDebugUtils.js:114 
handleLogEvent

3.
cleanup C:/Users/peek/AppData/Roaming/Brackets/extensions/user/brackets-synapse/modules/RemoteManager.js:165 (anonymous function)

4.
 WebSocket connection to 'ws://localhost:29735/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:965

**Comment by kooohei** [comment]
Please check permission  to the file.
code 530, It should was certainly permission relationship.

**Comment by p33k** [comment]
I use the same FTP Account that I used with eqFTP and it worked there. Permissions should be fine.

**Comment by kooohei** [comment]
ic that right, code 530 is not permission. that was 533.
FTP response code 530 "Requested actionnot taken."

Is not able to reproduce it in my environment.

I will take a look for a while
Can you try access to other server?

**Comment by p33k** [comment]
Same Problem with an other server of a different web hoster

**Comment by kooohei** [comment]
ah I under stand!
please change server setting, part of exclude to "., .." or empty.
".*" has bug..
