### ISSUE TITLE
Upload on Save

### ISSUE THREAD

**Issue by Dogacel** [kooohei/brackets-synapse#5]
I can't see any option about how does this extension upload files. I save files and nothing happens on host. When i save then disconnect than connect again, file discards the changes. It doesn't change, so it isn't updating via ftp. How does this update. Is it a problem with me ? Or should i wait 5mins or so ?

**Comment by kooohei** [comment]
do you use synapse of what version?
new version is 1.0.8
plz give me a error log on Developer tools if you can.

**Comment by Dogacel** [comment]
I found it. 'Dogac' is my Username
Exception in 'change' listener on FileSystem {_index: FileIndex, _watchedRoots: Object, _watchRequests: Array[0], _externalChanges: Array[0], _impl: Object…} TypeError: Cannot read property 'filter' of undefined TypeError: Cannot read property 'filter' of undefined
    at _fsChangeHandler (file:///C:/Users/Dogac/AppData/Roaming/Brackets/extensions/user/growlscript.brackets.classcompletion/CacheManager.js:341:26)
    at FileSystem.trigger (/utils/EventDispatcher.js:222:40)
    at FileSystem._fireChangeEvent (/filesystem/FileSystem.js:703:14)
    at Directory.eval (/filesystem/Directory.js:256:38)
    at FileSystem.eval (/filesystem/FileSystem.js:754:17)
    at _applyAllCallbacks (/filesystem/Directory.js:122:26)
    at Directory.eval (/filesystem/Directory.js:217:13)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:304:25)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:244:17)
/utils/EventDispatcher.js:225 Assertion failed:
/utils/EventDispatcher.js:224 Exception in 'change' listener on FileSystem {_index: FileIndex, _watchedRoots: Object, _watchRequests: Array[1], _externalChanges: Array[0], _impl: Object…} TypeError: Cannot read property 'filter' of undefined TypeError: Cannot read property 'filter' of undefined
    at _fsChangeHandler (file:///C:/Users/Dogac/AppData/Roaming/Brackets/extensions/user/growlscript.brackets.classcompletion/CacheManager.js:341:26)
    at FileSystem.trigger (/utils/EventDispatcher.js:222:40)
    at FileSystem._fireChangeEvent (/filesystem/FileSystem.js:703:14)
    at Directory.eval (/filesystem/FileSystemEntry.js:425:38)
    at FileSystem.eval (/filesystem/FileSystem.js:754:17)
    at _applyAllCallbacks (/filesystem/Directory.js:122:26)
    at Directory.eval (/filesystem/Directory.js:217:13)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:304:25)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:244:17)
/utils/EventDispatcher.js:225 Assertion failed:

**Comment by kooohei** [comment]
Dogac thx for feed back
When does appear the logs on devtools?
I want logs about the moment file is saved(upload)
and plz check your account has valid permission to the file.

Seemingly, your logs is brackets FileSystem Error.
perhaps, I think Project files positioning or some error.
Directly the logs does not matter for file could not uploaded

**Comment by Dogacel** [comment]
When i connect

**Comment by kooohei** [comment]
i see. but the logs does not show the error from Synapse.
Do you checked permission to file?

**Comment by kooohei** [comment]
uploaded fixed version.
plz check that.
